sudo: false
language: node_js
node_js:
  - stable
  - 8

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules/
    - packages/*/node_modules/
    - ${HOME}/.npm

install:
  - npm install

os:
  - linux

stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."

    - stage: gh-page
      script:
        - echo "gh-page  push..."
        - npm version
        - cd _demo
        - npm install
        - npm run build
        - cd ./dist
        - git init
        - git config user.name "${U_NAME}"
        - git config user.email "${U_EMAIL}"
        - git add .
        - git commit -m "demo-build"
        - git push --force --quiet https://${GIT_TOKEN}@${GH_REF} master:${PAGE_BRANCH}
        - echo "gh=page - end"

    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm version
        - npm run build
        - echo "NPM Building Finished."

      deploy:
        provider: npm
        email: 13129944389@163.com
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
